### ISSUE TITLE
Pasting chineese unicode characters hangs termbox

### ISSUE THREAD

**Issue by marcopeereboom** [nsf/termbox-go#115]
Pasting 語 in _demos/editbox.go causes termbox to hang.

That's it, nothing fancy.

Don't have time to dig into that right now.

**Comment by nsf** [comment]
What OS? Can't reproduce it on linux. But I haven't tried very hard.

**Comment by marcopeereboom** [comment]
I see it on bitrig/openbsd, osx and one of my guys sees it on windows (i think).

So I guess all of the not tested ones ;)

**Comment by marcopeereboom** [comment]
nsf any news on this?

**Comment by nsf** [comment]
Well, what can I do if I can't reproduce it. So, no news on that one.

**Comment by marcopeereboom** [comment]
This was magically fixed.
