### ISSUE TITLE
Backspace wrong escape sequence (linux)

### ISSUE THREAD

**Issue by japanoise** [nsf/termbox-go#145]
Hi, I noticed KeyBackspace is mapped to `^H`. While this may have been true historically, most terminals these days send an escape sequence beginning with `^[`. The effect of this is that you can't capture backspace events under most terminals.

**Comment by nsf** [comment]
There is KeyBackspace2 also. Sadly I haven't found anything "standard" for this key. I suggest using both KeyBackspace and KeyBackspace2 as "backspace".

E.g. https://github.com/nsf/godit/blob/master/view.go#L1210

**Comment by nsf** [comment]
Also I think your statement about escape sequence is incorrect. Backspace sends `^H`, which is ASCII "backspace" or `0x7F` which is ASCII DEL. If you have actual examples where terminal sends an esc sequence, it would be nice to know which. You can use `go run _demos/raw_input.go` to see what's being sent.

**Comment by japanoise** [comment]
You're correct. I think I was forgetting backspace2 or something. This bug hasn't reoccurred after following more "idiomatic" practices (i.e. actually reading the examples).
