### ISSUE TITLE
Can I Sniffing global keyboard events with termbox-go?

### ISSUE THREAD

**Issue by metalwood** [nsf/termbox-go#146]
Not only the current application, I need to listen keyboard events of global system.

**Comment by nsf** [comment]
Most likely no. Termbox only gets what it receives via terminal. If you want global events the way you can get them depends on the OS you're running. On linux you may look into X11 or even kernel events (evdev). On windows something in winapi, I'm not sure.

Termbox just interprets a stream of bytes it gets via terminal and on windows it uses windows console input events.
