### ISSUE TITLE
Need support for multiple keys pressed simultaneousely

### ISSUE THREAD

**Issue by kirhgoff** [nsf/termbox-go#147]
Now if you keep pressing button A and start pressing button D, you will stop getting A events and start getting D events, while A is still being pressed.

**Comment by nsf** [comment]
Impossible on terminals. On windows console it is possible though. It won't happen. My advice - whatever you do where you need this, stop using terminals for that.

**Comment by kirhgoff** [comment]
Thank you for you advice, was hoping to make console game. Can you give a direction or keywords  to find something to read about why it is not possible?

**Comment by nsf** [comment]
Terminals don't send any kind of events, all you get is just a stream of bytes, there are no "key press" or "key release" events, when user presses "a" all you get is byte "a". What bytes are sent to the terminal is up to a terminal, but most terminals won't spam "ad" if you hold both keys, they will send only the last pressed button. I don't have anything where you can read about it.

**Comment by kirhgoff** [comment]
Thank you
