### ISSUE TITLE
Breaks process execution on Windows 10 / Powershell

### ISSUE THREAD

**Issue by LarsFronius** [nsf/termbox-go#153]
For us we see the terminal window (e.g. Powershell) turn black on Init()
Specifically on
https://github.com/nsf/termbox-go/blob/b6acae516ace002cb8105a89024544a1480655a5/api_windows.go#L48
The syscall made here seems set the buffer size, which in our case stops execution and turning the shell unusable.
I don't have much more insight, ask me what you need that could be of help for fixing this.
I traced it down to the call mentioned with delve debugger, unfortunately I don't have a good hunch on how to fix this.

**Comment by nsf** [comment]
Well, maybe I'll take a look at it one day. It works on my windows 7 machine, haven't tried it (or I tried it and forgot) on windows 10. And obviously haven't tried it on powershell. Works from cmd and far manager.
