### ISSUE TITLE
Keyboard/mouse input only?

### ISSUE THREAD

**Issue by elliotchance** [nsf/termbox-go#162]
Is it possible to only capture and handle keyboard and mouse without any of the rendering?

**Comment by nsf** [comment]
No. Termbox is not an input capturing library. Although you can extract that code manually if you want to. It's not a big lib.

**Comment by arch-master** [comment]
@nsf Can you please provide a separate go library, maybe like `termbox-input`, that is only the input manager?

**Comment by nsf** [comment]
Do it yourself. 

But if I ever decide to do a big refactoring on termbox or something, I'll consider splitting it into two parts. It does make sense.
