### ISSUE TITLE
MouseHover Event

### ISSUE THREAD

**Issue by DavidGamba** [nsf/termbox-go#175]
Having a MouseHover Event would allow to trigger UI changes to highlight the Mouse position or provide some tooltips.
Currently it seems that capturing the Mouse location can only be done on a click or release mouse event.

**Comment by nsf** [comment]
Terminals don't have mouse motion events iirc.

**Comment by DavidGamba** [comment]
Sorry about opening an issue for it then :P I didn't see any similar issue so I though I would ask...

I wish more terminals were trying to move forward with extra features, like iTerm2 inline image.
