### ISSUE TITLE
API to change size of screen

### ISSUE THREAD

**Issue by varunrau** [nsf/termbox-go#179]
I'd like to be able to set a custom size, so that the entire terminal isn't taken over when termbox is active. Is that possible?

The current workaround I'm exploring is opening up a separate tmux pane and running the program there.

**Comment by nsf** [comment]
No, I can't see how this can be done. Termbox assumes it has full control over terminal. If it's not true then there is always a risk of being out of sync. Tmux as an option, or I suggest to forget about terminals and use alternative GUI options. Such as HTML. Don't go crazy over terminal interfaces, terminals are not the end of the world.

**Comment by varunrau** [comment]
ah bummer, oh well!
