### ISSUE TITLE
Wide unicode characters take two units

### ISSUE THREAD

**Issue by songgao** [nsf/termbox-go#18]
Hey, I was just trying out termbox (and it's great by the way!) and found out a problem for wide unicode characters. Actually it's a problem for wide runes displayed in fix-width font. My terminal (iTerm) prints wide characters twice as wide as ascii characters. As a result, if there's a wide rune, the drawn characters won't be aligned properly. Try this code:

``` go
package main

import (
    "github.com/nsf/termbox-go"
    "time"
)

func main() {
    err := termbox.Init()
    if err != nil {
        panic(err)
    }
    defer termbox.Close()

    cn := []rune{'你', '好', '，', '世', '界', '！'}
    en := []rune{'a', 'b', 'c', 'd', 'e', 'f'}
    for i := range cn {
        termbox.SetCell(i, 0, cn[i], termbox.ColorBlack, termbox.ColorWhite)
    }
    for i := range en {
        termbox.SetCell(i, 1, en[i], termbox.ColorRed, termbox.ColorWhite)
    }
    termbox.Flush()
    time.Sleep(5 * time.Second)
}
```

I'm not sure what should be changed to fix it yet. Should it 
- count wide runes as two characters in the buffer? (That would possibly produce overlapped characters)
- Or if a wide rune is in buffer, then all non-wide runes are also drawn 2x wide?
- Or provide an option on how runes are drawn?

**Comment by shia86** [comment]
I recommend to use `go-runewidth`
