### ISSUE TITLE
Init wrong size on Win7 cmd (non-English windows)

### ISSUE THREAD

**Issue by zsimple** [nsf/termbox-go#183]
I found the pull #168 Init a wrong buffer size on Win7 cmd (non-English windows).

When starting a termbox-go program, buffer size is too large for default cmd window.
![image](https://user-images.githubusercontent.com/9044544/35763815-7c90a17e-08ef-11e8-95a9-7b0faded0bda.png)
The buffer size shows:
![image](https://user-images.githubusercontent.com/9044544/35763817-8d53ff1a-08ef-11e8-9744-4333df8f44fa.png)

Below it the result use older version termbox-go, which looks prety good.
![image](https://user-images.githubusercontent.com/9044544/35763809-5bf04b22-08ef-11e8-8ad8-bc3f960f735a.png)

**Comment by nsf** [comment]
Well, if you can fix it that'd be nice. Also there are similar libraries which claim to be better, have a look: https://github.com/gdamore/tcell

**Comment by zsimple** [comment]
tcell looks wonderful, I played and found it doesnt works perfectly on my cmd either...

In fact I don't need display unicode character, so I decided to use termbox-go again, wih the old version(Sorry I don't have enough knowledge to fixed this issue now).
