### ISSUE TITLE
True color support

### ISSUE THREAD

**Issue by tombh** [nsf/termbox-go#184]
I couldn't see any previous discussion of this. I assume adding this would break backwards compatibility on `SetCell()` because enumerating 16 million attributes is crazy.

There's some good insight on true colour support and detection here: https://gist.github.com/XVilka/8346728

I can do the work to get a draft PR if there's desire for this. I need it for https://github.com/tombh/texttop

**Comment by nsf** [comment]
Adding more colors would require me to increase "Cell" struct size. I don't want to do that. Also I don't think anyone needs that many colors in a terminal. If you disagree, try alternative libraries, e.g.: https://github.com/gdamore/tcell.
