### ISSUE TITLE
Weird characters with ncurses 6.1

### ISSUE THREAD

**Issue by agostonbarna** [nsf/termbox-go#185]
After upgrading ncurses to v6.1 weird characters appear on the screen when I try to use [peco](https://github.com/peco/peco).

```
$ cat test.txt       
line 1
line 2
line 3
```

```
$ cat test.txt | peco
 �����������������������[%i%p1%dG                            [3 (1/1)]
line 1
line�2�������������������������������
����������������������������������  
line�3��[%i%p1%dG
Waiting for input...
�����������������������������  
```

Thanks to @mattn I learned that peco uses termbox-go under the hood
and that the issue might happen because terminfo was also modified with the latest ncurses upgrade.

infocmp diff:

```diff
45c45
< 	pairs= 32767.
---
> 	pairs= 65536.
173c173
< 	kmous= '\E[M'.
---
> 	kmous= '\E[<'.
190c190
< 	rmcup= '\E[?1049l'.
---
> 	rmcup= '\E[?1049l\E[23;0;0t'.
206c206
< 	smcup= '\E[?1049h'.
---
> 	smcup= '\E[?1049h\E[22;0;0t'.
```
---

ncurses version: 6.1.20180127
TERM: xterm-256color
OS: Arch Linux
Linux kernel: 4.14.20-1-lts, x86_64

peco/peco#446

**Comment by syui** [comment]
The operation seems to change also with `tmux` .

**Comment by agostonbarna** [comment]
Normally yes, but I did the test without tmux.

**Comment by cfstras** [comment]
Tested with Hyper, gnome-terminal, even with disabling all .profile&zshrc.
xterm and bare linux console work...

Did a diff of "set", found a workaround:

   TERM=xterm <my-program> #works!!!

Seems like the bug only gets triggered with TERM=xterm-256color

**Comment by cfstras** [comment]
Downgrading to `ncurses-6.0-20180121` did NOT work.
Downgrading to ncurses-6.0 (found on https://ftp.gnu.org/pub/gnu/ncurses/ ) WORKS.

For anyone on Arch Linux, I've created a PKGBUILD file that gets you going quickly:
https://gist.github.com/cfstras/f8634870126cb5b84c76a30200c2b603

**Comment by k2nr** [comment]
Same here with peco & opensuse tumbleweed. `TERM=xterm` worked for me

**Comment by kevinschoon** [comment]
Confirmed I am seeing this bug as well with ncurses 6.1 on Arch. It will effect anything using this lib including the many popular tools built on [termui](https://github.com/gizak/termui/). `TERM=xterm ./my-program` will fix the issue. It's not immediately clear to me what the long term fix for the issue is but I imagine the maintainer will have an idea..

```
4.15.5-1-ARCH
glibc 2.26-11
ncurses 6.1-3
```

**Comment by nsf** [comment]
I'll have a look at it this weekend. Hopefully won't forget about it.

**Comment by nsf** [comment]
Should work now. Ncurses 6.1 slightly altered the terminfo file format. Quoting man page:
```
       On occasion, 16-bit signed integers are not large enough.  With ncurses
       6.1,  a  new format is introduced by making a few changes to the legacy
       format:

       ·   a different magic number (0542)

       ·   changing the type for the number array from signed 16-bit  integers
           to signed 32-bit integers.
```

Although doc implies octal number (and original magic number is also specified in octal). What I see in terminfo files is just a little endian 16-bit number 542. Whatever...
