### ISSUE TITLE
Shift+Enter?

### ISSUE THREAD

**Issue by miguelmota** [nsf/termbox-go#204]
Is the Shift+Enter key combo supported?

**Comment by nsf** [comment]
No.

**Comment by miguelmota** [comment]
@nsf mind elaborating on why? (would like to understand)

**Comment by nsf** [comment]
Well initially I've made termbox in such a way that everything it offers in API works on all terminals. Over time additional and optional things were added (which I'm not a big fan of) such as 256 colors and things like that. But input was never extended in that regard. And I'm not really interested in developing termbox further. I'm surprised it's somewhat popular. I think more people should use HTML/JS for their UIs (not even a joke).

**Comment by miguelmota** [comment]
Thanks for the explanation
