### ISSUE TITLE
Panic: invalid interrupt on WSL Ubuntu

### ISSUE THREAD

**Issue by wolf99** [nsf/termbox-go#207]
I'm trying to use Hecate, which uses termbox, on WSL Ubuntu.
When running the application, it results in panic when `termbox.Init()`.
You can see the raised Hecate issue here https://github.com/evanmiller/hecate/issues/15
Unfortunately I don't know enough about go, or Linux, to understand whet the rest of the trace output means 😢 

```bash
$ hecate hecate_0.0.1_amd64.deb
panic: invalid argument

goroutine 1 [running]:
main.main()
        /Users/emiller/Code/gocode/src/github.com/evanmiller/hecate/hecate.go:187 +0x3d9

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 17 [select, locked to thread]:
runtime.gopark(0x5deb50, 0xc820028728, 0x597c78, 0x6, 0x443718, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820028728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820028728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by scrouthtv** [comment]
Is this still an issue for you?
Does this issue persist?

If yes, I would like to help you with it.

For me, your exact given commands are working with WSL Ubuntu.
What is your output of `wsl.exe -l -v`?

**Comment by scrouthtv** [comment]
Related: https://github.com/evanmiller/hecate/issues/15

**Comment by wolf99** [comment]
Honestly I cant recall what Hecate is nor why I was trying to use it 
Output of the suggested command currently shows Ubuntu at WSL version 2, but at the time I raised this issue it would have been Ubuntu on WSL version 1

**Comment by scrouthtv** [comment]
From what I can tell [evanmiller/Hecate](https://github.com/evanmiller/hecate) is a console hex editor. Upstream seems to have abandoned the project more or less, the last commit is almost four years ago and the last release is tagged 0.0.1

I tried the exact same procedure you described in the original issue with WSL Ubuntu WSL version 1 and everything worked as expected.

There haven't been any comments on the issue you opened on their page.

I'll consider it fixed?
