### ISSUE TITLE
Keybindings not working on FreeBSD

### ISSUE THREAD

**Issue by miguelmota** [nsf/termbox-go#218]
I run the demos but none of the keybindings work. I can't quit the demos either. I tested on a fresh install of FreeBSD. Any idea?

**Comment by nsf** [comment]
Hard to say, maybe try installing ncurses. Maybe termbox-go won't work on freebsd, I don't remember what I use in there when it comes to OS interaction. I don't maintain this library anymore. It's worth looking at better maintained alternatives such as https://github.com/gdamore/tcell.

**Comment by miguelmota** [comment]
Installing ncurses didn't help but the Go [tcell](https://github.com/gdamore/tcell) library works on FreeBSD so will switch to that. Feel free to close this issue or leave it open
