### ISSUE TITLE
build failure on gnu/hurd

### ISSUE THREAD

**Issue by pravi** [nsf/termbox-go#223]
There are many errors similar to

```
src/github.com/nsf/termbox-go/termbox.go:507:37: error: reference to undefined identifier ‘syscall.SYS_FCNTL’
 507 |  r, _, e := syscall.Syscall(syscall.SYS_FCNTL, uintptr(fd), uintptr(cmd),
```

From Debian GNU/Hurd maintainers,

> Such hardcoding is indeed deemed to fail: fcntl is not a system call on
> GNU/Hurd: since the implementation can be userland one really has to
> call the fcntl() function provided by glibc, as it really should on any
> reasonable Unix system.

Can you use fcntl() function provided by glibc here? 

Note: This was git master branch snapshot from 20160914 (current version in Debian)

**Comment by pravi** [comment]
It looks like an issue with gccgo on hurd.

**Comment by pravi** [comment]
Reported it here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956820

**Comment by scrouthtv** [comment]
There hasn't been any activity on their side, closing for now.
