### ISSUE TITLE
Copy-pastable line wrap

### ISSUE THREAD

**Issue by tigrawap** [nsf/termbox-go#226]
When splitting long line into several lines (and filling content cell by cell) it is not copy-paste friendly

There is always new line copy-pasted
Is there a way to actually line wrap when needed?

If not, directions on how/where to implement it in termbox itself are welcomes

**Comment by nsf** [comment]
It's not possible in termbox. Just because of abstractions used. Termbox doesn't preserve info about lines of text as it's just an array of 2d cells. And I believe similar libs have a similar problem, but maybe I'm wrong about that.

Solution: avoid using terminals. Terminals suck.

**Comment by scrouthtv** [comment]
Sorry for the late answer, but let me get this right:
You want to be able to select a multi-line text but not the entire lines and you don't want the line breaks to be in the selection?
So this is your problem:
![termselection](https://user-images.githubusercontent.com/23227405/98436051-6685c680-20d8-11eb-859f-dde479b77cb5.gif)

If you're still looking for a solution, here's something I hacked together:
![clipboard](https://user-images.githubusercontent.com/23227405/98448579-459b9080-212d-11eb-8643-53637483743b.gif)

Here is the source file in case you're interested: [clipboard.go.txt](https://github.com/nsf/termbox-go/files/5505255/clipboard.go.txt)

This basically consists of three things:
 - Any mouse press is recorded and added to a selection rectangle.
 - The selection rectangle is highlighted in the inverted style.
 - When the user presses the enter key, that region is copied to the clipboard.

With this technique, you still cannot intercept `C-Ins` (although you can intercept `C-S-c`. Also, keep in mind that what I'm doing here is not a real terminal selection but just a highlighted area.

Let me know if this helped you!
