### ISSUE TITLE
Mouse select fails on newlines

### ISSUE THREAD

**Issue by 89z** [nsf/termbox-go#237]
Using this program:

<https://github.com/nsf/termbox-go/blob/2ff63027/_demos/256ramp.go>

I get this output:

~~~
004 005 006 007 008 009       004 005 006 007 008 009
010 011 012 013 014 015       010 011 012 013 014 015   
~~~

However, if I select the two lines, and paste somewhere else, I get this:

~~~
004 005 006 007 008 009       004 005 006 007 008 009                                                                   010 011 012 013 014 015       010 011 012 013 014 015
~~~

Notice the newline is stripped out.

**Comment by scrouthtv** [comment]
For me, the newline is there on 
 - both the old & the new windows terminal
 - xterm and termite

Could you kindly specify your system?

**Comment by 89z** [comment]
Windows 10

**Comment by scrouthtv** [comment]
Are you using plain cmd? The new Terminal? Third-party terminal emulator?
I can't reproduce this at all

**Comment by 89z** [comment]
I am using PowerShell with Windows Terminal - can you give more details about your setup

**Comment by scrouthtv** [comment]
https://github.com/microsoft/terminal/issues/1073
