### ISSUE TITLE
Mouse click events can't handle > 223 rows/columns

### ISSUE THREAD

**Issue by cookieo9** [nsf/termbox-go#32]
The mouse event can only have MouseX, and MouseY values that are in the range 0 to 222 (and -33 should a coordinate be greater than 222).

This happens because the event is sent to termbox is a sequence with a single 8-bit character for each of the X and Y locations and with 33 added to them. If a click occurs outside the range, then 0 is sent as the location, so termbox reports it as -33 (due to the adjustments it makes).

Looking at http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#Mouse%20Tracking , the likely cause of this is that termbox is using X10 compatibility mode, which behaves in this manner. According to this page there are several solutions, but they might be to difficult to work with in termbox, or might drop compatability, so the simplest solution might just be to document for the user this limitation, as 222 rows/columns might be big enough for most people.

I've only tested this on OS X, using xterm, but I suspect it affects linux, and bsd systems as well. I have no idea about the situation on Windows.

**Comment by nsf** [comment]
Termbox uses xterm and urxvt extended modes now if terminal can handle them. Which overcomes this limitation, but it won't work everywhere. To see how exactly your terminal reports mouse coordinates use `_demos/raw_input.go`. If you see something like: `"\x1b[<0;76;32m"`, then it's the xterm extended mode. Urxvt one looks similar, it doesn't have a "<" character in the message, e.g.: `"\x1b[35;76;32m"`. X10 mode starts with `"\x1b[M"`.

See commit: https://github.com/nsf/termbox-go/commit/4aa457c414d0392fb8981c975a0b
