### ISSUE TITLE
Control key modifier

### ISSUE THREAD

**Issue by maxnordlund** [nsf/termbox-go#46]
When I was looking through the different keys you can listen on I noticed that control wasn't a modifier. This struck me as a bit odd, and even more so when not all normal keys could be found as a control variant. To be more specific there are, as far as I can see, no ctrl+arrow key combination.

What is the reason for this design? Could a control modifier be added without breaking old code? Either way could you add ctrl+arrow keys in the mean time?

Thanks for this awesome library, and for your time

**Comment by ryanavella** [comment]
> There will be still a plenty of them which do not work, e.g. Ctrl+F1. Also many of the combos such as Ctrl+Shift+ are simply impossible in the terminal.

Just curious, is this why Ctrl+1 and Ctrl+9 are not currently provided by termbox-go?

**Comment by nsf** [comment]
> Just curious, is this why Ctrl+1 and Ctrl+9 are not currently provided by termbox-go?

Ctrl+<key> combinations in terminals are implemented via sending some single byte. I might be wrong about this, but pressing Ctrl+1 sends just "1" and pressing Ctrl+9 also sends just "9". I have no idea why. There's raw input demo in the demos directory, you can try it yourself.
