### ISSUE TITLE
NetBSD support

### ISSUE THREAD

**Issue by selb** [nsf/termbox-go#68]
NetBSD is not currently supported out of the box, but this is easy to fix:

    $ cp syscalls_openbsd.go syscalls_netbsd.go

I also verified that the values in there matched the system headers. I would also guess that syscalls_freebsd.go would work as syscalls_dragonfly.go; I can look into this more if you'd like.

**Comment by nsf** [comment]
Added `syscalls_netbsd.go`. Well, if you really need it, sure, take a look at dragonfly bsd, but I don't use it and I don't know anyone who does.

**Comment by selb** [comment]
I don't really need DragonFly support, so I'll leave it be. Thanks for adding NetBSD. :)
