### ISSUE TITLE
go get install line fails

### ISSUE THREAD

**Issue by ktm5j** [nsf/termbox-go#73]
Hey I was trying to install termbox-go using the go get command 

```
kmiles@sita ~/src/go/gocurses/termbox-go $ sudo go get -u github.com/nsf/termbox-go
# github.com/nsf/termbox-go
/usr/lib/go/src/pkg/github.com/nsf/termbox-go/api.go:268: function ends without a return statement
```

If I add a "return event" line at the end of that function I can compile..  However, there's a very similar looking function immediately below with a line at the end saying panic("unreachable"), so I'm not sure the end of the PollRawEvent() function should even be reachable..  

I'm not very well versed in go so I'm not really sure what's going on, but I thought I'd let you guys know.

**Comment by nsf** [comment]
Just update your Go compiler. It's probably very old. What `go version` says?

**Comment by ktm5j** [comment]
It's version 1.0.2, it's what was in the debian stable repos, I see that's pretty old though.  I'll take your word that it's my compiler, I'll try again tomorrow when I get a chance with a newer version

Thanks for the reply!

**Comment by ktm5j** [comment]
Yup, that did the trick.  Thanks
