### ISSUE TITLE
termbox unit test

### ISSUE THREAD

**Issue by ericwq** [nsf/termbox-go#79]
i try to write some test for my termbox based application. is that possible to abstract an interface for api.go? with that interface, it's easy to write mock implementation to test the result.

**Comment by nsf** [comment]
You can make your own abstract API. Termbox's interface is small anyway. If you ask whether there are helpers for that - no.

**Comment by ericwq** [comment]
ok. if i finished the API interface, can i send it to you?

**Comment by nsf** [comment]
I don't need it. I see no reason why termbox would include something like that.

**Comment by kalafut** [comment]
@ericwq Post your mock interface somewhere. I'd use it.

**Comment by ericwq** [comment]
@kalafut  https://github.com/ericwq/trembox-mock. sorry@nsf.

**Comment by kalafut** [comment]
@ericwq Thanks. This looks about like what I was going to end up writing and will get me 90% of the way there.

**Comment by ericwq** [comment]
i'd like that help you.
