### ISSUE TITLE
Key-up event

### ISSUE THREAD

**Issue by JoelOtter** [nsf/termbox-go#83]
Perhaps I'm missing something, but I can't work out how to process a key being held down or released.

I had thought that a KeyEvent would be repeatedly fired if a key was held down, but this doesn't appear to be the case. Because of this, and the fact there's no key-up event, it makes it (seemingly) impossible to detect if a key is held down. I think either one of these (key up event or repeated firing of events) would be great to have.

Please do let me know if I'm being an idiot. Feel free to use the word 'idiot'. Thanks!

**Comment by nsf** [comment]
Terminals don't report that kind of information. It's possible on windows, but not on *nix. In terminals a key press event is just a utf-8 sequence sent over the wire, no additional info at all, just the character itself.

**Comment by JoelOtter** [comment]
Thanks for the quick response. Disappointing, though I guess I should have
known that.

Is what I'm looking to do realistically not possible, then?

**Comment by nsf** [comment]
With terminals - definitely not. On MS Windows you can do that. Well, on linux you can try to capture input using some third-party mechanism like https://en.wikipedia.org/wiki/Evdev. But this is largely unportable. The best solution is to just use X11, i.e. write a real gui app. Maybe isn't as easy in Go, but possible.

**Comment by JoelOtter** [comment]
I guess the way around it is just to do a non-blocking event poll, and let the terminal emulator's key-repeat take care of it. Obviously it's a little inelegant and unpredictable, but it does sort of work.

Thanks for your help! I'll close this now.
