### ISSUE TITLE
Uncontrolled buffer growth

### ISSUE THREAD

**Issue by ssl1** [nsf/termbox-go#85]
After some hours of working the program is taking up a lot of RAM. It looks like charbuf in file termbox_windows.go growth uncontrolled. 
```
func append_diff_line(y int) int {
	n := 0
	for x := 0; x < front_buffer.width; {
...
		charbuf = append(charbuf, char_info{attr: attr, char: char[0]})
...
		if !is_cjk && w == 2 {
			charbuf = append(charbuf, char_info{attr: attr, char: ' '})
		}
...
```
The problem is fixed by clear charbuf
```
func prepare_diff_messages() {
	// clear buffers
	diffbuf = diffbuf[:0]
	charbuf = charbuf[:0]

	var diff diff_msg
...
```

**Comment by nsf** [comment]
But I haven't tested it, I'm not on a windows machine, please test it.

Yep, it was a bug introduced by me. Sorry.
