### ISSUE TITLE
Termbox panics on Esc keypress when input mode is InputMouse

### ISSUE THREAD

**Issue by ferbivore** [nsf/termbox-go#97]
The following code initializes Termbox and loops infinitely - at least until you hit Esc, at which point it aborts with a `panic: unreachable` at [line 372 in `termbox.go`](https://github.com/nsf/termbox-go/blob/master/termbox.go#L372):

```go
package main
import "github.com/nsf/termbox-go"
import "os"

func main() {
    os.Setenv("TERM", "xterm")
    termbox.Init()
    defer termbox.Close()
    termbox.SetInputMode(termbox.InputMouse)
    for {
        termbox.PollEvent()
    }
}
```

This may be platform specific - I'm on OS X and haven't tested it on Windows or Linux yet. The `os.Setenv` call is a fix for issue #80. This only seems to happen when the input mode is InputMouse - the others work fine.

**Comment by nsf** [comment]
Yeah, I fixed that bug in C version: https://github.com/nsf/termbox/blob/master/src/termbox.c#L313-L319

Will commit the same for Go version in just a few minutes.

**Comment by nsf** [comment]
P.S. To be clear. `termbox.InputMouse` is not a valid input mode. It must be one of the InputEsc or InputAlt and optionally InputMouse. Patch will force setting it to Esc if you don't provide on of esc or alt.

**Comment by nsf** [comment]
Should be fixed by https://github.com/nsf/termbox-go/commit/9914d1c5284376
