### ISSUE TITLE
Additional mouse events?

### ISSUE THREAD

**Issue by JoelOtter** [nsf/termbox-go#98]
I'm wondering if there's a way to read additional mouse events in Termbox, for example, mouse-up, or mouse drag. Some terminals seem to support them (I know one of xterm's modes supports mouse-drag, for example) but I'm not sure if there's a cross-platform way to do it.

**Comment by nsf** [comment]
Maybe one day. C version of the termbox surprisingly has mouse-up events. I guess I'll backport it one day. Have no time really.

**Comment by JoelOtter** [comment]
You're a hero, thank you!
